//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASnK.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegisteredEvents
    {
        public int RegisteredEventId { get; set; }
        public int EventId { get; set; }
        public string Email { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Country { get; set; }
        public System.DateTime ArivalDate { get; set; }
        public System.TimeSpan ArivalTime { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual tbl_Events tbl_Events { get; set; }
    }
}
